In [1]:
import numpy as np

In [2]:
# Creatring numpy arrays from Python List

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([3.14,4,2,5.6])

array([3.14, 4.  , 2.  , 5.6 ])

In [6]:
np.array([1,2,3,4,5], dtype='float32') # specify data type

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
a1 = np.array([1,2,3,4])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a2.shape # return col and row

(2, 3)

In [12]:
a2.ndim # The number of dimensions of the array

2

In [13]:
a2.dtype

dtype('int32')

In [14]:
a2.size # return total element in array

6

In [15]:
# Creating number arrays : zeros , ones , full , arange, linepace

In [16]:
# zeros

In [17]:
np.zeros([2,4]) # shape , dtype , order . Return new array of give shape and type .At the same time fill with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros([2,4]).dtype

dtype('float64')

In [20]:
np.zeros([2,4],dtype= int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
# ones

In [22]:
np.ones([3,5],dtype= int) # return new array with fill one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.ones((3,5),dtype= float) # return new array with fill one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Creating an array filled  with linear sequence
# Starting at 0, ending at 20 , stepping by 2
# this is similar to the built-in  range() function
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
b = np.arange(0,20,2)

In [26]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [28]:
# full

In [29]:
np.full((3,5),5) # return new array , filled with fill value

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [30]:
# linspace - linear space

In [31]:
#Create an array of five values evenly space bettwen 0 and 1

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# random

In [34]:
np.random.random((4,4))

array([[0.78060202, 0.10668944, 0.65379018, 0.96490794],
       [0.23617935, 0.55875453, 0.31704961, 0.48737646],
       [0.93254165, 0.65997767, 0.53056675, 0.40640853],
       [0.40241815, 0.11788191, 0.87851235, 0.57356256]])

In [35]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [36]:
np.random.normal(0,1,(3,3)) # mean , standard deviation 

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [37]:
np.random.randint(1,10,5)

array([8, 3, 1, 1, 5])

In [38]:
np.random.randint(1,10,(3,5))

array([[6, 6, 7, 9, 5],
       [2, 5, 9, 2, 2],
       [8, 4, 7, 8, 3]])

In [39]:
np.random.rand(4,4)

array([[0.1289263 , 0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514, 0.65632959]])

In [40]:
# array indexing & slicing
# one - dimensional subarray

In [41]:
x1 = np.random.randint(20,size=6)

In [42]:
x1

array([17,  5,  9,  3,  0,  5])

In [45]:
x1[4] , x1[0] , x1[-1]

(0, 17, 5)

In [46]:
# Multi-dimensional array

In [47]:
x2 =  np.random.randint(10,size=(3,4))

In [48]:
x2

array([[0, 1, 2, 4],
       [2, 0, 3, 2],
       [0, 7, 5, 9]])

In [49]:
x2[1,2]

3

In [50]:
x2[1,2] = 6

In [51]:
x2

array([[0, 1, 2, 4],
       [2, 0, 6, 2],
       [0, 7, 5, 9]])

In [52]:
# slicing x[start:stop:step]

In [53]:
x1

array([17,  5,  9,  3,  0,  5])

In [54]:
x1[0:3]

array([17,  5,  9])

In [55]:
# every other element, every 2 step

In [56]:
x1[::2]

array([17,  9,  0])

In [57]:
x2

array([[0, 1, 2, 4],
       [2, 0, 6, 2],
       [0, 7, 5, 9]])

In [58]:
# two rows , three columns
x2[:2,:3]

array([[0, 1, 2],
       [2, 0, 6]])

In [59]:
x2[:,:2]

array([[0, 1],
       [2, 0],
       [0, 7]])

In [60]:
# Reshaping of array & transpose

In [62]:
grid = np.arange(1,10)
grid.shape

(9,)

In [63]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
x = np.array([1,2,3])

In [65]:
x.shape

(3,)

In [66]:
x.reshape((1,3)).shape

(1, 3)

In [68]:
# transpose

In [70]:
x = np.array([[1.,2.],[3.,4.]])

In [71]:
x

array([[1., 2.],
       [3., 4.]])

In [72]:
x.T

array([[1., 3.],
       [2., 4.]])

In [73]:
# Array contactenation and splitting

In [74]:
x = np.array([1,2,3])
y =  np.array([3,2,1])

In [75]:
np.concatenate((x,y)) # axis = 0  : row by default

array([1, 2, 3, 3, 2, 1])

In [76]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [78]:
# vstack

In [80]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

In [81]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [82]:
# horizontally stack  the arrays : hstack

In [83]:
y = np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [84]:
# splitting of arrays

In [86]:
x = np.array([1,2,3,99,69,3,2,1])
x1 , x2, x3 =  np.split(x,[3,5])

In [87]:
x1, x2 ,x3 

(array([1, 2, 3]), array([99, 69]), array([3, 2, 1]))

In [88]:
# broadcasting and vectorized operations

In [89]:
a = np.arange(3)

In [90]:
a

array([0, 1, 2])

In [91]:
a + 5 # broadcasting

array([5, 6, 7])

In [92]:
b  = np.ones((3,3))

In [93]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
a.shape , b.shape


((3,), (3, 3))

In [95]:
 a+ b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [97]:
 a * b 

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [98]:
c = np.arange(3).reshape(3,1)

In [99]:
c

array([[0],
       [1],
       [2]])

In [100]:
c + a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [101]:
# Manipulating  and comparing arrays
# aggregation 

In [102]:
list_number = [1,2,3]

In [103]:
ll = np.array(list_number)

In [104]:
ll

array([1, 2, 3])

In [105]:
sum(ll) # python sum()

6

In [106]:
np.sum(ll) # Numpu sum()

6

In [107]:
# Create a massitive Numpy array
massitive_array =  np.random.random(10000)
massitive_array[:5]
massitive_array.shape

(10000,)

In [110]:
%timeit  sum(massitive_array) # Python build-in fuction sum
%timeit np.sum(massitive_array) #Numpy's np.sum

873 µs ± 80 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
8.9 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [111]:
np.mean(massitive_array)

0.5012860612205885

In [112]:
np.max(massitive_array)

0.9999709462497284

In [113]:
np.min(massitive_array)

2.0027530115096503e-05

In [114]:
dog_height = np.array([600,470,170,430,300])

In [115]:
np.std(dog_height) # standard deviation

147.32277488562318

In [116]:
np.var(dog_height) # variance

21704.0

In [118]:
# sorting arrays
# np.sort uses an quicksort algorithms

In [119]:
x =  np.array([2,1,3,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [120]:
# a related function is argsort. which instead returns the indices of the sorted elements
np.argsort(x) # retrun index of sorted element

array([1, 0, 2, 3, 4], dtype=int64)

In [121]:
# sorting along rows and colums

In [122]:
np.random.seed(42)
MatA = np.random.randint(0,10,size=(4,6))

In [123]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [124]:
np.sort(MatA,axis=0) # columms

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [125]:
np.sort(MatA,axis=1) # row

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [126]:
# linear algebra

In [128]:
A = np.array([[1,2,3],
              [4,5,6],
             [7,8,9]])

In [127]:
B = np.array([[6,5],
             [4,3],
             [2,1]])

In [129]:
# A 3x3 dot product B (3x2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [130]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [131]:
# B dot A
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [132]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [133]:
a4

array([[[[8, 0, 9, 2, 6],
         [3, 8, 2, 4, 2],
         [6, 4, 8, 6, 1],
         [3, 8, 1, 9, 8]],

        [[9, 4, 1, 3, 6],
         [7, 2, 0, 3, 1],
         [7, 3, 1, 5, 5],
         [9, 3, 5, 1, 9]],

        [[1, 9, 3, 7, 6],
         [8, 7, 4, 1, 4],
         [7, 9, 8, 8, 0],
         [8, 6, 8, 7, 0]]],


       [[[7, 7, 2, 0, 7],
         [2, 2, 0, 4, 9],
         [6, 9, 8, 6, 8],
         [7, 1, 0, 6, 6]],

        [[7, 4, 2, 7, 5],
         [2, 0, 2, 4, 2],
         [0, 4, 9, 6, 6],
         [8, 9, 9, 2, 6]],

        [[0, 3, 3, 4, 6],
         [6, 3, 6, 2, 5],
         [1, 9, 8, 4, 5],
         [3, 9, 6, 8, 6]]]])